/* empty css                      */import{a as m,S as d,i}from"./assets/vendor-B4VkUtbg.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const y="data:image/svg+xml,%3csvg%20xmlns='http://www.w3.org/2000/svg'%20width='24'%20height='24'%20viewBox='0%200%2024%2024'%20fill='none'%20stroke='%23fafafb'%20stroke-width='1.5'%20stroke-linecap='round'%20stroke-linejoin='round'%3e%3cpolygon%20points='7.86%202%2016.14%202%2022%207.86%2022%2016.14%2016.14%2022%207.86%2022%202%2016.14%202%207.86%207.86%202'%20/%3e%3cline%20x1='15'%20y1='9'%20x2='9'%20y2='15'%20/%3e%3cline%20x1='9'%20y1='9'%20x2='15'%20y2='15'%20/%3e%3c/svg%3e",h="https://pixabay.com/api/",b="16287282-bb4aa79813232011e036abcfd";function v(a){return m.get(h,{params:{key:b,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9}}).then(s=>s.data)}const c=document.querySelector(".gallery"),u=document.querySelector(".loader"),w=new d(".gallery a",{captionsData:"alt",captionDelay:250});function L(a){const s=a.map(({webformatURL:r,largeImageURL:l,tags:e,likes:t,views:o,comments:g,downloads:f})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}">
        <img class="gallery-image" src="${r}" alt="${e}" />
      </a>
      <ul class="gallery-stats">
        <li class="gallery-stat"><span class="stat-label">Likes</span><span class="stat-value">${t}</span></li>
        <li class="gallery-stat"><span class="stat-label">Views</span><span class="stat-value">${o}</span></li>
        <li class="gallery-stat"><span class="stat-label">Comments</span><span class="stat-value">${g}</span></li>
        <li class="gallery-stat"><span class="stat-label">Downloads</span><span class="stat-value">${f}</span></li>
      </ul>
    </li>`).join("");c.insertAdjacentHTML("beforeend",s),w.refresh()}function x(){c.innerHTML=""}function S(){u.classList.add("is-visible")}function q(){u.classList.remove("is-visible")}const p=document.querySelector(".form");function n(a){i.error({message:a,position:"topRight",theme:"dark",backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"#fafafb",iconUrl:y,progressBarColor:"#b51b1b",maxWidth:432})}p.addEventListener("submit",E);function E(a){a.preventDefault();const s=a.currentTarget.elements["search-text"].value.trim();if(!s){i.warning({message:"Please enter a search query!",position:"topRight"});return}x(),S(),v(s).then(r=>{if(r.hits.length===0){n("Sorry, there are no images matching your search query. Please try again!");return}L(r.hits)}).catch(r=>{n(`Something went wrong: ${r.message}`)}).finally(()=>{q(),p.reset()})}
//# sourceMappingURL=index.js.map
